defaultautosort: false
defaultsortingpattern: LEFT_TO_RIGHT_TOP_TO_BOTTOM
locale:
  lang: en
  country: GB
cleaningItem:
  ==: org.bukkit.inventory.ItemStack
  v: 2230
  type: IRON_HOE
active: true
durability: true
openinventoryeventmode: false
consumablesrefill: true
blockrefill: true
cleanInventorypermissionactive: true
cooldown:
  active: true
  time: 5000
blacklist:
  stacking:
    - air
  inventory:
    - furnace
categories:
  order:
    - AlphaBackAsc
    - IsBlock
  words:
    - ==: WordCategory
      name: StoneWord
      word: stone
    - ==: WordCategory
      name: StairWord
      word: stair
    - ==: WordCategory
      name: SlabWord
      word: slab
    - ==: WordCategory
      name: CarpetWord
      word: carpet
  lists:
    - ==: ListCategory
      name: StoneList
      list:
        - stone
        - stone_bricks
        - mossy_stone_bricks
        - cracked_stone_bricks
        - chiseled_stone_bricks
        - smooth_stone
        - granite
        - polished_granite
        - diorite
        - polished_diorite
        - andesite
        - polished_andesite
        - gravel
    - ==: ListCategory
      name: DirtList
      list:
        - dirt
        - grass_block
        - grass_path
        - coarse_dirt
        - podzol
        - mycelium
  master:
    - ==: MasterCategory
      name: StoneMaster
      list:
        - StoneList
        - StoneWord
